apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBXimMgFt6G35+sx+/G+tgbC0yS2iDeKMl8olnud8S4hEzg91oa9WxCiqaA/kivDVANzjMPYEJ6ncMimWw4PJvv+PYwwysd2Q5DXFcdRg8KLHuyXhYOqVhfDg5jUnKqL1/yQuD2nRbFtbSuVijjbCLSgRGvgP99WZxOWX4ZNYkigKOhN2+TjVC0ylXcRdbMprAfanvfdZDm4aaGv1hoN/U9bRTc1G3xPg27ly/Hm84D3Wthb8S7Mijj55wccZrZ4xoepmZUDeMFBZraRFmJzYB0NsaYmwDEOU7JHQHEvgXeDpnFD2FHCx2PCEB2McBPzb8R2Dh9AhTiHphK8bCjFqvBEysv9+w799uS9qkkbzFUpBSyDdBjUeApKZr8rzfEPY7mmvw7hSrrJDdNyuFVqcIWVlEjTusIwb7F7tHZtQkkLQmM4xeQM7ObluRuzSbg/Bxl85fmfcDo1Nco9ETyV/iVhfwZgdsZDge6m2ZaWS6L062UC1QadD1oRT1tvttZOHG0t69S4iqaJ+pWtqSAAburfi7t4b8U37817Dn02BxBWoX5xvrqy+3LaZB8+3HDj5a1K+khRf/9Q/uxdtNkInVwiEJ63LNwl3A9PLfeYYa9ikA4VURH/hMzKfHPA/t3OfSDJdiAbONAVT4zFf6FwHzd2D8CwoYblkd0xM5Ql6S5vrJInsbBBxzuwMVGiakvLqNUQXkQwa6k3Q==
    DB_USER: AgCxQR4+UPvu95kmaIyws6aiUv4RnvDaWpjwFa9IuuXBgZlEuWvnTSKSryUGHtUhsRrbnfLc09Cwq8EPOaA4FyUxoVMWSSBaFwZanuKaGiaBs9a8lhfZ7aIe1Ou5OrjfXmzzqW478a+QzNBrc8Z58k3bFtuFOE7q/erpA/jFKTUbjBH52j5bh6apAmTan+B+X2Bf6J7rcqhzU9w0VEM4OyAbV6ExqY4g7w7QelOjl6aN4ZqQJV0O1r794Nw/CsdzQR4w6gh15q25i1QgnfWfOTlvc4/9mN06ZdKYbTXm+/hqBN3d8lBqmjqc8feDR64zaSqos+Oadg2riSUVM1oDexDaZZY5xnFYhEG+GdqhMpIYU5ZgIMM9ycEbt4r5h1kLchUr+4LfTKSxkjZG7sjGnutkmMv1Tx1gbSdixqv6ypCv+rQLIUAH9P6E+arNB9xAQ6ogbB/3Ks+Jx0GhalV+S+eqO1SrrH4uTvmbdR7p8qH8KFcqbqBNPcYIUeXHmPOnlDYd7f0go5cjkdT9LxQaCn0/7so1n/4PNZ14VqZ8PuE7LPQHZYCA00MafXNVN3XdOrTzlnAAbv8/uBm4wzvA1K1gAq/MDWP+aQ5xs2p1nIy57aEZjyg16zEXrjP6QbuAcIQ0/c04aiiohIkIuyHoLW+Kyrrqy8cVrint8tHPlsxGfwSg3blW23Wq2lvcaTHS9QRDdWYEkJj4Bw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

